#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Part_Posalji.Resource", IsApplication=true)]

namespace Part_Posalji
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_default = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int collor_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int main_icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ociscena_rega = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int zone_btn_style = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int List_Automat_History = 2131099655;
			
			// aapt resource value: 0x7f060015
			public const int List_SMS_Main_History = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int Pay_Automat_Main = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int Pay_SMS_Main = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int btn_change_time = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btn_save_time = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int button1 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int dialog_btn = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int editText_message = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int editText_number = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int edit_time_automat = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int sendSMS = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow1 = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int textView = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int text_view1 = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int vuki_btn = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int zona1_btn = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int zona2_btn = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int zona3_btn = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int zona4_1_btn = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int zona4_2_btn = 2131099667;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_fragment_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int List_Represent = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Pay_Automat_Main_Enter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Pay_Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Pay_SMS_Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int Pay_Automat_Main = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int Pay_SMS_Main = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int SMS = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int app_name = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int editText_message = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int editText_number = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int sendSMS = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int valid_check = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public const int vuki_number = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int zona1_number = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int zona2_number = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int zona3_number = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int zona4_1_number = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int zona4_2_number = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_splash = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int collored_button = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int main_btn = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int registration_view = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int zone_view = 2131034116;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
